// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxsD85-VkWSysccHK8HTCUNKPcdVRbzE',
    appId: '1:848075218250:android:3aeca23388466bd195f5b3',
    messagingSenderId: '848075218250',
    projectId: 'integrate-967fa',
    databaseURL: 'https://integrate-967fa-default-rtdb.firebaseio.com',
    storageBucket: 'integrate-967fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnAWoYQ9xHOWYKQGFCz_U-U7vm4DgCpLs',
    appId: '1:848075218250:ios:ae2065c51aa8ce7395f5b3',
    messagingSenderId: '848075218250',
    projectId: 'integrate-967fa',
    databaseURL: 'https://integrate-967fa-default-rtdb.firebaseio.com',
    storageBucket: 'integrate-967fa.appspot.com',
    iosClientId: '848075218250-t6e9s9opb22fp56upgefps6ham0elb4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
